# Generated by Django 4.2.5 on 2023-09-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_alter_apartment_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type',
            field=models.CharField(choices=[('CBI', 'Colocation Bail Individuel'), ('CBS', 'Colocation Bail Solidaire')], default='CBI', max_length=10),
            preserve_default=False,
        ),
    ]
